### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by JisongXie** [eriklindernoren/PyTorch-YOLOv3#157]
I use the code to train on my custom dataset. All input images size are 608 x 608, and there are 20 classes, each image has only a bounding box.  I follow the structions to custom model and dataset. And I meet a training error，
`RuntimeError: CUDA error: device-side assert triggered. `
The error occurs uncertainly, for example, in Epoch 2 Batch 1200, or in Epoch 3 Batch 2000, while the previous epoch can finish training fluently.
Following pictures are the detailed error.
![error](https://user-images.githubusercontent.com/28192557/57171978-9b162380-6e4c-11e9-9f21-82b41179844f.jpg)
It seems that it occurs in build_targets function in model.py, the build_target function is in the utils/utils.py. This error is so difficult to debug!

**Comment by readicculus** [comment]
I'm getting same exact error ill update if i figure out issue

**Comment by JisongXie** [comment]
It seems clearly, that the error is index out of bounds, and that it occurs on predictions. Maybe sometimes the output predictions is empty and the code doesn't take this into account. I need time to understand the whole pipeline clearly to fix the bug.

**Comment by ghimiredhikura** [comment]
I'm also getting exact same error on my custom dataset. this is index out of bound error, will update if i solve it.

**Comment by readicculus** [comment]
I fixed it... i wasn't normalizing my inputs.  I have my own data loader and need to input yolo format
cetner_x,center_y,w,h in [0,1] for labels.  I was using pixel values.

**Comment by MaTao215** [comment]
I met the same problem too.Have you fixed it?

**Comment by QQ2737499951** [comment]
I met the same problem too.Have you fixed it?

"D:\Program Files\Python368\python.exe" B:/PyTorch/PyTorch-YOLOv3/train.py
Namespace(batch_size=8, checkpoint_interval=1, compute_map=False, data_config='data/coco.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, model_def='cfg/yolov3.cfg', multiscale_training=True, n_cpu=8, pretrained_weights=None)
data/coco/train.txt data/coco/val.txt
data/coco/images/train.jpg
data/coco/images/000000000034.jpg
data/coco/images/000000000030.jpg
data/coco/images/000000000042.jpg
data/coco/images/000000000049.jpg
data/coco/images/000000000025.jpg
data/coco/images/000000000036.jpg
C:/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "B:/PyTorch/PyTorch-YOLOv3/train.py", line 107, in <module>
    loss, outputs = model(imgs, targets)
  File "D:\Program Files\Python368\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "B:\PyTorch\PyTorch-YOLOv3\models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "D:\Program Files\Python368\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "B:\PyTorch\PyTorch-YOLOv3\models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "B:\PyTorch\PyTorch-YOLOv3\utils\utils.py", line 317, in build_targets
    class_mask[b, best_n, gj, gi] = (pred_cls[b, best_n, gj, gi].argmax(-1) == target_labels).float()
RuntimeError: CUDA error: device-side assert triggered

**Comment by dongfangduoshou123** [comment]
> It seems clearly, that the error is index out of bounds, and that it occurs on predictions. Maybe sometimes the output predictions are empty and the code doesn't take this into account. I need time to understand the whole pipeline clearly to fix the bug.

Hi, 
Have you fixed this bug?

**Comment by readicculus** [comment]
its most likely an issue with your labels.  make sure your labels are in the correct format.  I had the same issue and fixed it by fixing my labels.  Are you training on your own dataset?

**Comment by lzl4525** [comment]
how to fix it

**Comment by SmartGx** [comment]
> It seems clearly, that the error is index out of bounds, and that it occurs on predictions. Maybe sometimes the output predictions are empty and the code doesn't take this into account. I need time to understand the whole pipeline clearly to fix the bug.

I met the same problem.Have you fixed it?

**Comment by Arthur77Wang** [comment]
Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:

# Separate target values
    b, target_labels = target[:, :2].long().t()
    gx, gy = gxy.t()
    gw, gh = gwh.t()
    gi, gj = gxy.long().t()
    ########## TODO(arthur77wang):
    gi[gi < 0] = 0
    gj[gj < 0] = 0
    gi[gi > nG] = nG
    gj[gj > nG] = nG
    ###################
    # Set masks
    obj_mask[b, best_n, gj, gi] = 1
    noobj_mask[b, best_n, gj, gi] = 0

This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

**Comment by BloomBerry** [comment]
same problem too.
---- [Epoch 0/100, Batch 0/14786] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 13           | 26           | 52           |
| loss       | 71.552628    | 69.287781    | 70.698685    |
| x          | 0.081982     | 0.095761     | 0.097411     |
| y          | 0.114656     | 0.081447     | 0.083638     |
| w          | 2.447639     | 0.842779     | 1.058129     |
| h          | 2.727762     | 1.390022     | 1.789845     |
| conf       | 65.440392    | 66.154922    | 66.964203    |
| cls        | 0.740200     | 0.722845     | 0.705461     |
| cls_acc    | 1.89%        | 0.00%        | 1.47%        |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.463119     | 0.486062     | 0.475699     |
| conf_noobj | 0.466011     | 0.474434     | 0.481249     |
+------------+--------------+--------------+--------------+
Total loss 211.53909301757812
---- ETA 3 days, 18:36:37.682694
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=59 : device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/jang/virtualenv/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/jang/virtualenv/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/utils/utils.py", line 324, in build_targets
    iou_scores[b, best_n, gj, gi] = bbox_iou(pred_boxes[b, best_n, gj, gi], target_boxes, x1y1x2y2=False)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/utils/utils.py", line 199, in bbox_iou
    b1_x1, b1_x2 = box1[:, 0] - box1[:, 2] / 2, box1[:, 0] + box1[:, 2] / 2
RuntimeError: CUDA error: device-side assert triggered

**Comment by kaikaizhu** [comment]
@BloomBerry 
I met the same problem.Have you fixed it?

**Comment by zhaopeng0103** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

I met the same problem, too. But after I use the method mentioned above, the error does not appear. Thank you!

**Comment by susanhc** [comment]
解决方法参考：https://blog.csdn.net/susanhc/article/details/93876762

**Comment by kaikaizhu** [comment]
When I ran the program with a single gpu, everything was fine, but when I joined multiple gpus, I made this mistake, and my label started at 0.

**Comment by khgapa** [comment]
@kaikaizhu When I use multiple gpus, I have same problem.

**Comment by qwe3208620** [comment]
我减少coco检测类别的时候遇到这个问题，还没有解决

**Comment by qwe3208620** [comment]
I encountered this problem when reducing the coco detection category, which has not been solved yet.

**Comment by qwe3208620** [comment]
> When I ran the program with a single gpu, everything was fine, but when I joined multiple gpus, I made this mistake, and my label started at 0.
请问你是怎么确认的label从0开始了  我减少训练类别 没有改动代码 为什么label也会溢出呢

**Comment by LifeIsSoSolong** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

I solve this problem using your methed, thanks

**Comment by SWHL** [comment]
I meet the same problem.
```python
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/test/SWHL/MetaPyTorch-YOLOv3-master/train.py", line 125, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/test/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/SWHL/MetaPyTorch-YOLOv3-master/models.py", line 311, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/test/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/test/SWHL/MetaPyTorch-YOLOv3-master/models.py", line 233, in forward
    ignore_thres=self.ignore_thres,
  File "/home/test/SWHL/MetaPyTorch-YOLOv3-master/utils/utils.py", line 301, in build_targets
    obj_mask[b, best_n, gj, gi] = 1
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by kirilcvetkov92** [comment]
I found a small workaround here :

Replace : 

```
 obj_mask[b, best_n, gj, gi] = 1
 noobj_mask[b, best_n, gj, gi] = 0

```
with :

```
gi = torch.clamp(gi, 0, noobj_mask.size()[2]-1)
gj = torch.clamp(gj, 0, noobj_mask.size()[3]-1)
obj_mask[b, best_n, gj, gi] = 1
noobj_mask[b, best_n, gj, gi] = 0
```

**Comment by NeuralFlux** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

Solved my problem, thank you so much!

**Comment by GangHu1993** [comment]
When i used multi-gpu, I have same problem. When I used single gpu, no problem.

**Comment by chenhuanan** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

The root cause of the problem is that there is no correct label format, not this one. If you solve the problem as above, you will not be able to train the desired result

**Comment by zhudd-hub** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~
优秀

**Comment by xiaoxiaoshu111** [comment]
> When i used multi-gpu, I have same problem. When I used single gpu, no problem.

I also have the same problem... Did you solve it...

**Comment by bchugg** [comment]
I had the same problem on the ultralytics yolov3 implementation. The issue for me was that, even while my bounding box coordinates were normalized (between 0 and 1), the coordinates sometimes still specified a box that fell outside the image. For example, if we have 
```
x_center = 0.88 
y_center = 0.27 
width = 0.2
height = 0.3 
```

then this was throwing an error because the right side of the bounding box has x coordinate greater than one, i.e., x_center + width/2 > 1. 

Hope this helps someone!

**Comment by ujsyehao** [comment]
you can refer to https://github.com/ujsyehao/yolov3-multigpu

**Comment by TonyAlpha12** [comment]
> When I ran the program with a single gpu, everything was fine, but when I joined multiple gpus, I made this mistake, and my label started at 0.

I meet the sample problem too,have you fix it?

**Comment by TonyAlpha12** [comment]
> When i used multi-gpu, I have same problem. When I used single gpu, no problem.

你解决这个问题了吗，我的也是单卡跑没毛病，多卡一跑就报错了：noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0  RuntimeError: CUDA error: device-side assert triggered

**Comment by arctanxxx** [comment]
> I had the same problem on the ultralytics yolov3 implementation. The issue for me was that, even while my bounding box coordinates were normalized (between 0 and 1), the coordinates sometimes still specified a box that fell outside the image. For example, if we have
> 
> ```
> x_center = 0.88 
> y_center = 0.27 
> width = 0.2
> height = 0.3 
> ```
> 
> then this was throwing an error because the right side of the bounding box has x coordinate greater than one, i.e., x_center + width/2 > 1.
> 
> Hope this helps someone!

I just met the problem you said. I can run it after I modify it according to the above method, but there is another problem after running for some time. How to solve it? Thank you

**Comment by arctanxxx** [comment]
> same problem too.
> ---- [Epoch 0/100, Batch 0/14786] ----
> +------------+--------------+--------------+--------------+
> | Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
> +------------+--------------+--------------+--------------+
> | grid_size | 13 | 26 | 52 |
> | loss | 71.552628 | 69.287781 | 70.698685 |
> | x | 0.081982 | 0.095761 | 0.097411 |
> | y | 0.114656 | 0.081447 | 0.083638 |
> | w | 2.447639 | 0.842779 | 1.058129 |
> | h | 2.727762 | 1.390022 | 1.789845 |
> | conf | 65.440392 | 66.154922 | 66.964203 |
> | cls | 0.740200 | 0.722845 | 0.705461 |
> | cls_acc | 1.89% | 0.00% | 1.47% |
> | recall50 | 0.000000 | 0.000000 | 0.000000 |
> | recall75 | 0.000000 | 0.000000 | 0.000000 |
> | precision | 0.000000 | 0.000000 | 0.000000 |
> | conf_obj | 0.463119 | 0.486062 | 0.475699 |
> | conf_noobj | 0.466011 | 0.474434 | 0.481249 |
> +------------+--------------+--------------+--------------+
> Total loss 211.53909301757812
> ---- ETA 3 days, 18:36:37.682694
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=59 : device-side assert triggered
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [0,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> Traceback (most recent call last):
> File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1741, in
> main()
> File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1735, in main
> globals = debugger.run(setup['file'], None, None, is_module)
> File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1135, in run
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "/home/jang/PycharmProjects/PyTorch-YOLOv3/train.py", line 105, in
> loss, outputs = model(imgs, targets)
> File "/home/jang/virtualenv/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/jang/PycharmProjects/PyTorch-YOLOv3/models.py", line 259, in forward
> x, layer_loss = module[0](x, targets, img_dim)
> File "/home/jang/virtualenv/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/jang/PycharmProjects/PyTorch-YOLOv3/models.py", line 188, in forward
> ignore_thres=self.ignore_thres,
> File "/home/jang/PycharmProjects/PyTorch-YOLOv3/utils/utils.py", line 324, in build_targets
> iou_scores[b, best_n, gj, gi] = bbox_iou(pred_boxes[b, best_n, gj, gi], target_boxes, x1y1x2y2=False)
> File "/home/jang/PycharmProjects/PyTorch-YOLOv3/utils/utils.py", line 199, in bbox_iou
> b1_x1, b1_x2 = box1[:, 0] - box1[:, 2] / 2, box1[:, 0] + box1[:, 2] / 2
> RuntimeError: CUDA error: device-side assert triggered

I just met the problem you said. Have you solved it? Thank you

**Comment by hlchen1043** [comment]
Exactly same problem here, training on custom data, single GPU, also report the problem after start running it at some time

**Comment by AlvinWen428** [comment]
I have solved this issue. Please check your labels and make sure that the normalized labels must satisfy 0< x_center +/- width <1 and 0 < y_center +/- height <1. Note that it must be $<$, not $<=$.

**Comment by zxin8218** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

I solve this problem using your methed too, thank you

**Comment by JessonKang** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

I solved this problem too，thank you very much!

**Comment by mama110** [comment]
check labels and the problem will be solved.

**Comment by bisonliao** [comment]
I met this problem too. 
create_custom_model.sh with great class number than actual number can solve it.  
COCO dataset has 80 classes. I create_custom_model 90 and generate yolo3-bison.cfg.  
then I train with yolo3-bison.cfg and coco dataset , it can avoid this problem

**Comment by bisonliao** [comment]
sorry.  I met this problem too. 
for me, it is because my label files contain improper class indices.

**Comment by bisonliao** [comment]
> I met this problem too.
> create_custom_model.sh with great class number than actual number can solve it.
> COCO dataset has 80 classes. I create_custom_model 90 and generate yolo3-bison.cfg.
> then I train with yolo3-bison.cfg and coco dataset , it can avoid this problem

sorry.  for me, it is because my label files contain improper class indices.

**Comment by sharoseali** [comment]
> > Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> > ```
> > b, target_labels = target[:, :2].long().t()
> > gx, gy = gxy.t()
> > gw, gh = gwh.t()
> > gi, gj = gxy.long().t()
> > ########## TODO(arthur77wang):
> > gi[gi < 0] = 0
> > gj[gj < 0] = 0
> > gi[gi > nG - 1] = nG - 1
> > gj[gj > nG - 1] = nG - 1
> > ###################
> > # Set masks
> > obj_mask[b, best_n, gj, gi] = 1
> > noobj_mask[b, best_n, gj, gi] = 0
> > ```
> > 
> > 
> > This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~
> > 优秀



> > Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> > ```
> > b, target_labels = target[:, :2].long().t()
> > gx, gy = gxy.t()
> > gw, gh = gwh.t()
> > gi, gj = gxy.long().t()
> > ########## TODO(arthur77wang):
> > gi[gi < 0] = 0
> > gj[gj < 0] = 0
> > gi[gi > nG - 1] = nG - 1
> > gj[gj > nG - 1] = nG - 1
> > ###################
> > # Set masks
> > obj_mask[b, best_n, gj, gi] = 1
> > noobj_mask[b, best_n, gj, gi] = 0
> > ```
> > 
> > 
> > This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~
> 
> I solved this problem too，thank you very much!

Can you please explain? At which exact line number, these code lines should be added?

**Comment by hongjianyuan** [comment]
> 在Ultralytics yolov3的实现上，我遇到了



> 在Ultralytics yolov3的实现上，我遇到了同样的问题。对我来说，问题是，即使我的边界框坐标已标准化（介于0和1之间），有时坐标仍会指定一个超出图像范围的框。例如，如果我们有
> 
> ```
> x_center = 0.88 
> y_center = 0.27 
> width = 0.2
> height = 0.3 
> ```
> 
> 那么这将引发错误，因为边界框的右侧的x坐标大于1，即x_center + width / 2> 1。
> 
> 希望这对某人有帮助！

How to standardize the data, I have now made the data (center_x, center_y, w, h)

**Comment by RRL-dev** [comment]
> Came across too. Maybe it's because of lacking some boundary checking when the code was parsing your label files. Several ground truth boxes might partly outside image after +-*/.... I added rude boundary assignments in utils/utils.py, build_targets func:
> 
> ```
> b, target_labels = target[:, :2].long().t()
> gx, gy = gxy.t()
> gw, gh = gwh.t()
> gi, gj = gxy.long().t()
> ########## TODO(arthur77wang):
> gi[gi < 0] = 0
> gj[gj < 0] = 0
> gi[gi > nG - 1] = nG - 1
> gj[gj > nG - 1] = nG - 1
> ###################
> # Set masks
> obj_mask[b, best_n, gj, gi] = 1
> noobj_mask[b, best_n, gj, gi] = 0
> ```
> 
> This aims to avoid gi[i] and gj[i] exceeding bound of size[2, 3] of noobj_mask. You would make some more precise corrections~

Thank you. A real issue for out of image bounding box. Great and easy solution.

**Comment by Flova** [comment]
This happens when the bounding box is outside the image.
Reasons are, that the box coordinates are not normalized (between 0 and 1) or the box is normalized but at a position like 1.5.
An upcoming image augmentation pull request will likely result in the discarding of out of image labels as a side effect.
I think the issue is solved and therefore close it. Feel free to reopen for further questions,

**Comment by qqsuhao** [comment]
我英文不好，就直接用中文来写了。
我也遇到了这个问题，但是我的只会在model.py中的‘loss_conf_obj = self.bce_loss(pred_conf[obj_mask], tconf[obj_mask])’这一行报错RuntimeError: CUDA error: device-side assert triggered，可能是因为我修改了model.py的部分代码。然后我最近似乎找到了问题的根源所在。
- 在源程序的utils/datasets.py中的第132行，作者每间隔10次会将输入图片大小随机缩放，这会导致此时的输入图像尺寸不再是416。但是问题在于作者在创建Yololayer的时候，通过解析.cfg文件，已经提前将YoloLayer中的img_dim初始化为416（见源程序第75行和第77行）。之后在第119行，作者使用这个img_dim去求解self.stride，也就是从模型输入到模型输出特征图的缩放倍数。后面这个缩放倍数要被用于缩放anchor，进而被用于确定预测结果的位置。但是我们刚才说了，作者每间隔10次会将输入图片大小随机缩放，但是yoloLayer的时候并没有更新输入图片大小的语句，从而造成stride每隔10次都会求错。stride求解错误并不会直接导致程序崩溃，只有label的位置比较特殊，经过错误stride得到的运算结果才刚好可能超出输出结果的尺度范围，造成程序崩溃。这也就是为什么很多人报错都是随机出现的错误，并不是程序一运行就会出错。
- 解决办法：作者每间隔10次会将输入图片大小随机缩放是为了增加模型的鲁棒性；要想改正，要么把源程序的utils/datasets.py中的132-133行注释掉，要么修改model.py，让yoloLayer中的img_dim随着输入图像的变化进行更新。

---
除此以外，在utils/utils.py中我还发现比较有趣的问题：在 build_targets函数中，也就是第329行，作者直接使用`.float()`将BoolTensor转换为FloatTensor。但是我稍加实验，发现这种方法转换以后，转换结果并不是将true转为1.0，false转为0.0；而是如下图
![image](https://user-images.githubusercontent.com/31772922/112268705-5864cb00-8cb2-11eb-9654-918afb203ca3.png)
我也不是很清楚原所在，但是无疑这会导致Loss求解错误，而且会错得很离谱。不过幸好求解loss的时候self.obj_scale要远小于self.noobj_scale，可以减轻这种错误的影响。
最好将源代码改成如下这样：
`tconf = FloatTensor(nB, nA, nG, nG).fill_(0)`
`tconf[obj_mask] = 1            # 置信度的真值`

**Comment by rajeshroy402** [comment]
I followed this document - https://github.com/pytorch/pytorch/#from-source and build it.
I will share you the specs.
I have Nvidia driver 470.x.x with Cuda 11.4.x installed for my UBUNTU 20.04 LTS system.
I didn’t find` conda install -c pytorch magma-cuda114` so went with` conda install -c pytorch magma-cuda112`
Rest all the installation was smooth.
Still, if I try to run something, I get the below-quoted errors:

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
----------------------------


--------------------------------------------------------------------------------------------

home/assertst/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: 
    Found GPU%d %s which is of cuda capability %d.%d.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is %d.%d.
    
  warnings.warn(old_gpu_warn.format(d, name, major, minor, min_arch // 10, min_arch % 10))
Device Used:  NVIDIA GeForce GT 730
Capability:  (3, 5)
<class 'darknet.Darknet'>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/assertst/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/assertst/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "nephro.py", line 88, in processResult
    output = self.model(Variable(img), self.CUDA)
  File "/home/assertst/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/assertst/nephroplus/darknet.py", line 319, in forward
    x = self.module_list[i](x)
  File "/home/assertst/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/assertst/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
File "/home/assertst/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/assertst/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 756, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/home/assertst/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1472, in leaky_relu
    result = torch._C._nn.leaky_relu_(input, negative_slope)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
