### ISSUE TITLE
train issue:shape is invaid for input of size

### ISSUE THREAD

**Issue by xiayanqian** [eriklindernoren/PyTorch-YOLOv3#174]
hello,I have two problems when I train my own data.These problems may be stupid but I tried and can not solve them.
1.When I trained with pretrained weights darknet53.conv.74,this happens:
` File "train.py", line 64, in <module>
    model.load_darknet_weights(opt.pretrained_weights)
  File "D:\PyTorch-YOLOv3-master\models.py", line 315, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 4365559`
I download(2019.5.9) the darknet53.conv.74 from pjreddie.com instead of using the .sh file.

2. When I trained without weights,it happens:
`RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 4.00 GiB total capacity; 2.87 GiB already allocated; 14.35 MiB free; 61.96 MiB cached)`
my GPU is GTX 1050 4G，maybe it's not enough for pytorch-yolov3?I have set batch=1
subdivisions=1 random=0 in the yolov3-custom.cfg.

**Comment by xiayanqian** [comment]
I check my yolov3-custom.cfg by https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/52,
I set classes=1 and filter prior to [yolo] seems to have been set 18 automatically.

**Comment by xiayanqian** [comment]
by https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/45 
I loaded yolov3.weights instead of darknet53.conv.74,seems that prombles 1 have been solved,and the '.txt' files in 'labels' shouldn't be empty or error occurs.
so is there any difference between 'yolov3.weights' and 'darknet53.conv.74'?
and problem 2,anyone can give me some suggestions?what's your GPUs?May RTX2060 6G satisfy the requirement?

**Comment by MichaelT800** [comment]
My GPU: RTX2080, MEMORY: 8G, the batch_size is set to 4 (default 8 sometimes encounters insufficient memory)
I wish you all the best

**Comment by xiayanqian** [comment]
Thank you very much! I checked the train.py and the test.py,found the batch_size is set 8 default ,I changed it to 2 then the training woks.I thought the batch size is set in yolov3-custom.cfg but it seems that the batch in the cfg is useless.

> My GPU: RTX2080, MEMORY: 8G, the batch_size is set to 4 (default 8 sometimes encounters insufficient memory)
> I wish you all the best

**Comment by weihua04** [comment]
I have  resolved the problem by rebuild the yolov3-custom.cfg  following the command "bash create_custom_model.sh <num-classes> ".   Hope help
