### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by houjun0322** [eriklindernoren/PyTorch-YOLOv3#324]
RuntimeError: CUDA error: device-side assert triggered happend when train on costom data conversed from widerface dataset.

**Comment by Songyyan** [comment]
Hello, can you solve this problem? I have encountered the same problem, I don't know how to solve it. I would like to ask you, thank you very much！

**Comment by sabrinatuli** [comment]
I have also encountered the same problem.

**Comment by JsBlueCat** [comment]
RuntimeError: CUDA error: device-side assert triggered

**Comment by AntoineMath** [comment]
same pb here with custom training

**Comment by alsawaf** [comment]
same problem here anyone has a solution ?

**Comment by DJever23** [comment]
anybody fix it? I also meet this error

**Comment by sabrinatuli** [comment]
For me, it was the invalid annotation for dataset or missing. I fixed the
dataset and it worked.

**Comment by DJever23** [comment]
Thanks for your reply. I have fixed it by using the method in https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/157.
Anyway, thanks a lot.

**Comment by Flova** [comment]
This happens due to invalid or out of bounds annotations. See #157 for further discussion.
