### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered   when training yolov3 using raw coco data

### ISSUE THREAD

**Issue by LifeIsSoSolong** [eriklindernoren/PyTorch-YOLOv3#383]
when I try to train yolov3 one epoch using raw coco data, I come across this error : reduce failed to synchronize: device-side assert triggered.
1.one gpu , rtx2080 8G
2.assert coco data labels all belong [0,1]
3.I have try to set smaller lr(1e-5 1e-6), but no use
4.I debug the error , it's because   pred_conf[obj_mask] =[None, None, ..]  and  tconf[obj_mask]=[1,1,1,...] which is normal. So the None value in pred_conf casued the error .
But pred_conf is computed by sigmoid function ,why return None ??

who can give me some advice ,thanks .

**Comment by LifeIsSoSolong** [comment]
I set batch_size=4 because one 8G gpu is not enough for batchsize=8.

**Comment by LifeIsSoSolong** [comment]
here is pred_conf and tconf in last 3 iter before error arise:

pred_conf[obj_mask] :  tensor([0.1126, 0.0536, 0.1194, 0.0995, 0.0565, 0.0488, 0.1040, 0.1544, 0.1336,
        0.0699, 0.0753, 0.1008, 0.0791, 0.0720, 0.0976, 0.1216, 0.1118, 0.0888,
        0.0694, 0.1339, 0.0856, 0.0729, 0.0658, 0.0574, 0.0519, 0.0622, 0.0547,
        0.0479, 0.0579, 0.1001, 0.0903, 0.0554, 0.0545], device='cuda:0',
       grad_fn=<IndexBackward>)
tconf[obj_mask]:  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')
pred_conf[obj_mask] :  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0',
       grad_fn=<IndexBackward>)
tconf[obj_mask]:  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')
pred_conf[obj_mask] :  tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       device='cuda:0', grad_fn=<IndexBackward>)
tconf[obj_mask]:  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       device='cuda:0')

**Comment by gcbitren** [comment]
i have met the problem and wasted a lot of time to solve it. Luckily i have solved this problem by set the parameter 'n_cpu' which should be less than you cpu cores. so please first check you cpu core numbers and then set the parameter n_cpu
