### ISSUE TITLE
cuda out of memory issue

### ISSUE THREAD

**Issue by YoonSungLee** [eriklindernoren/PyTorch-YOLOv3#539]
Hi, I wanted to use this repo because I wanted to compare some models' preformance in object detection field. So, I used this repo for transfer learning with my custom dataset in pycharm env with RTX 2080 Ti and Window 10. But, I'm not able to finish my transfer learning, because whenever I run this code, I got the error: 'cuda out of memory'.
I lowered batch size from 8 to 4, from 4 to 2, but It is not able to solve this problem. Also, I think it is not problem about my custom dataset size, because I have just 1000 images train dataset and this repo uses dataloader with batch_size.

How can I solve this problem???

**Comment by YoonSungLee** [comment]
Oh, I solved this problem.

**Comment by stwirth** [comment]
> Oh, I solved this problem.

How>

**Comment by YoonSungLee** [comment]
> > Oh, I solved this problem.
> 
> How?

When I first used repo, I ran the code referring to various issues, but this was the problem. I solved the problem by downloading the repo again and just applying the pull request below. It will work.

https://github.com/eriklindernoren/PyTorch-YOLOv3/pull/412

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
