### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by DJever23** [eriklindernoren/PyTorch-YOLOv3#550]
Hi, when I use CrowdHuamn dataset to train model with this code,I met a error as follows:

/opt/conda/conda-bld/pytorch_1565287025495/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1565287025495/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/dengjie/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengjie/dengjie/Paper/detection/PyTorch-YOLOv3/models.py", line 262, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/dengjie/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengjie/dengjie/Paper/detection/PyTorch-YOLOv3/models.py", line 189, in forward
    ignore_thres=self.ignore_thres,
  File "/home/dengjie/dengjie/Paper/detection/PyTorch-YOLOv3/utils/utils.py", line 307, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
RuntimeError: CUDA error: device-side assert triggered

I have convert the format of CrowdHuman dataset to COCO, which includes the path of images and labels, I also changed yolov3.cfg.I don't know how to fix this error,could you help me ?

**Comment by sabrinatuli** [comment]
I have also encountered same type of problem with WIDER FACE dataset when converted to COCO format. Make sure all the values for bounding box (x,y,w,h) are >0 and <1 or the annotation labels do not have any invalid values or missing value. Hope it helps.

**Comment by DJever23** [comment]
> I have also encountered same type of problem with WIDER FACE dataset when converted to COCO format. Make sure all the values for bounding box (x,y,w,h) are >0 and <1 or the annotation labels do not have any invalid values or missing value. Hope it helps.

Thanks for your reply. I have fixed it by using the method in issue #157.
Anyway, thanks a lot.

**Comment by Flova** [comment]
This happens due to invalid or out of bounds annotations. See #157 for further discussion.
