### ISSUE TITLE
CUDA Assertion error when trying to run on multiple GPUs

### ISSUE THREAD

**Issue by saurabh-2905** [eriklindernoren/PyTorch-YOLOv3#584]
I am trying to use this architecture to make it compatible with Fisheye images with rotated bounding boxes. I have written the code which works fine on single GPU but it is giving me 'RuntimeError: Caught RuntimeError in replica 0 on device 0' and 'RuntimeError: CUDA error: device-side assert triggered' when trying to use with Multiple GPUs.

I have 4 'GeForce GTX 1080 Ti' GPUs on my university server which I am trying to use remotely. I wish to access the first 2 GPUs for running this code.

I tried setting the ['CUDA_LAUNCH_BLOCKING'] = "1" but it is taking forever to load the data. I also tried setting ´num_workers=0` in dataloader which I read on one of the PyTorch forum discussion but the problem still persists

I have made the following changes to the code: [https://gitlab.informatik.uni-bremen.de/digipath/band-saurabh/-/tree/rotated](https://gitlab.informatik.uni-bremen.de/digipath/band-saurabh/-/tree/rotated)

I am using following part of the code to run on multiple GPUs:

```python
import os
#os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"
from torch.nn import DataParallel

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    os.makedirs("output", exist_ok=True)
    os.makedirs("checkpoints", exist_ok=True)

    # Get data configuration
    data_config = parse_data_config(opt.data_config)
    train_path = data_config["train"]
    valid_path = data_config["valid"]
    train_annpath = data_config["json_train"]
    valid_annpath = data_config["json_val"]
    class_names = load_classes(data_config["names"])

    if len(class_names) == 80:
        class_80 = True
    else:
        class_80 = False

    # Initiate model
    model = Darknet(opt.model_def).to(device)
    model.apply(weights_init_normal)

    # If specified we start from checkpoint
    if opt.pretrained_weights:
        if opt.pretrained_weights.endswith(".pth"):
            model.load_state_dict(torch.load(opt.pretrained_weights))
        else:
            model.load_darknet_weights(opt.pretrained_weights)

    #Use multiple GPUs
    #model = DataParallel(model)

    #Check if multiple GPUs available
    if torch.cuda.device_count() > 1:
        print("Let's use", torch.cuda.device_count(), "GPUs!")
        # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs
        model = DataParallel(model)
```

Following is the exact error and its original traceback. I would really use some help. Thanks in advance.

> /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [0,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=710 : device-side assert triggered
Traceback (most recent call last):
  File "/localdata/saurabh/.local/Python3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/localdata/saurabh/.local/Python3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sband/.vscode-server/extensions/ms-python.python-2020.11.358366026/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/sband/.vscode-server/extensions/ms-python.python-2020.11.358366026/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/sband/.vscode-server/extensions/ms-python.python-2020.11.358366026/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/localdata/saurabh/.local/Python3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/localdata/saurabh/.local/Python3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/localdata/saurabh/.local/Python3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/localdata/saurabh/yolov3/train.py", line 131, in <module>
    loss, outputs = model(imgs, targets)
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.

Original Traceback (most recent call last):
  

>  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py",
line 60, in _worker
    output = module(*input, **kwargs)
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722,
 in _call_impl
    result = self.forward(*input, **kwargs)
  File "/localdata/saurabh/yolov3/models.py", line 287, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/localdata/saurabh/yolov3/yol/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722,
 in _call_impl
    result = self.forward(*input, **kwargs)
  File "/localdata/saurabh/yolov3/models.py", line 205, in forward
    iou_scores, class_mask, obj_mask, noobj_mask, tx, ty, tw, th, tangle, tcls, tconf = build_targets(
  File "/localdata/saurabh/yolov3/utils/utils.py", line 405, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
RuntimeError: CUDA error: device-side assert triggered

**Comment by justinshaohi** [comment]
hi,have you sovled this question?

**Comment by saurabh-2905** [comment]
Hello, 

Yes I found the solution to this in one of the previous issues #157 

However, this is the solution that worked for me. You just need to introduce boundary conditions as the code is not build to run on multiple gpus.

```Python
b, target_labels = target[:, :2].long().t()
gx, gy = gxy.t()
gw, gh = gwh.t()
gi, gj = gxy.long().t()
########## TODO(arthur77wang):
gi[gi < 0] = 0
gj[gj < 0] = 0
gi[gi > nG - 1] = nG - 1
gj[gj > nG - 1] = nG - 1
###################
# Set masks
obj_mask[b, best_n, gj, gi] = 1
noobj_mask[b, best_n, gj, gi] = 0
```

**Comment by justinshaohi** [comment]
@saurabh-2905 thanks,good man.
