### ISSUE TITLE
Unable to find installation candidates for torchvision (0.8.2) during poetry install

### ISSUE THREAD

**Issue by zhengpengen** [eriklindernoren/PyTorch-YOLOv3#713]
When I do ```pip3 install poetry --user```, all requirements are already satisfied. However, when I do poetry install, I'm always met with the error mentioned in the title.

## Context

- [X] I have installed this repo manually and the issue occurred on this commit: 7bee67f

- [ ] I have installed this repo via `PIP` and the issue occurred on version: 
- [ ] The issue occurred when using the following .cfg model:
    - [ ] `yolov3`
    - [ ] `yolov3-tiny`
    - [ ] `CUSTOM`

## Necessary Checks

- [X] The issue occurred on the newest version

- [X] I couldn't find a similar issue here on this project's github repo
- [ ] If the issue is CUDA related (CUDA error), I have tested and provided the traceback also when CUDA is turned off 
- [X] I have provided all tracebacks or printouts in ```Text Form``` 
- [ ] In case, the issue occurred on a custom .cfg model, I have provided the model down below

## Expected behavior

Poetry install should install the environment successfully.

## Current behavior

After running ```poetry install``` I get:
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing torchvision (0.8.2)

  RuntimeError

  Unable to find installation candidates for torchvision (0.8.2)

  at ~\AppData\Roaming\Python\Python38\site-packages\poetry\installation\chooser.py:72 in choose_for
       68│
       69│             links.append(link)
       70│
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│
       76│         # Get the best link

## Steps to Reproduce

1. Current PyTorch version: 1.8.1 with Cuda 11.1
2. Current Python version: 3.8.10
3. Currently torchvision version: 0.9.1+cu11.1
4. CUDA version: 11.3
5. Platform: Windows 10
6. Followed all steps to on installing from source description except used conda and not pip3 to install poetry since pip3 was giving errors
7. run ```poetry install``` on \PyTorch-YOLOV3 (the main repo folder)
...

## Possible Solution

I had ideas about updating the PyTorch and other torchvision versions in ```poetry.lock``` such as:
torchvision = [
    {file = "torchvision-0.8.2-cp36-cp36m-macosx_10_9_x86_64.whl", hash = "sha256:86fae370d222f76ad57c57c3bee03f78b8db727743bfb4c1559a3d395159cea8"},
    {file = "torchvision-0.8.2-cp36-cp36m-manylinux1_x86_64.whl", hash = "sha256:951239b5fcb911dbf78c1385d677f5f48c7a1b12859e3d3ec287562821b17cf2"},
    {file = "torchvision-0.8.2-cp37-cp37m-macosx_10_9_x86_64.whl", hash = "sha256:24db8f4c3d812a032273f68563ad5dbd724f5bfbed523d0c6dce8cede26bb153"},
    {file = "torchvision-0.8.2-cp37-cp37m-manylinux1_x86_64.whl", hash = "sha256:b068f6bcbe91bdd34dda0a39e8a26392add45a3be82543f6dd523b76484fb56f"},
    {file = "torchvision-0.8.2-cp38-cp38-macosx_10_9_x86_64.whl", hash = "sha256:afb76a66b9b0693f758a881a2bf333ed97e3c0c3f15a413c4f49d8dd8bd21307"},
    {file = "torchvision-0.8.2-cp38-cp38-manylinux1_x86_64.whl", hash = "sha256:cd8817e9197fc60ebae37162a445db90bbf35591314a5767ad3d1490b5d65b0f"},
    {file = "torchvision-0.8.2-cp39-cp39-macosx_10_9_x86_64.whl", hash = "sha256:1bd58acc3366ec02266aae56a7a752d43ef07de4a6ba420c4f907d0c9168bb8c"},
    {file = "torchvision-0.8.2-cp39-cp39-manylinux1_x86_64.whl", hash = "sha256:976750a49db2e23dc5a1ed0b5c31f7af51ed2702eee410ee09ef985c3a3e48cf"},
]
and
[[package]]
name = "torch"
version = "1.7.1"
description = "Tensors and Dynamic neural networks in Python with strong GPU acceleration"
category = "main"
optional = false
python-versions = ">=3.6.2"

But I'm not sure where to find all the shl files and hash encryption and such

**Comment by jaagut** [comment]
Thank you for reporting your issue!

The missing version of `torchvision` definitely exists (See here: https://pypi.org/project/torchvision/0.8.2/)

My first guess is, that `PIP` itself or `poetry` (although already installed, as described in your issue) are not up to date and therefore can not find the specified version of `torchvision`.
You can update them as follows using `--upgrade`:

```
pip3 install pip poetry --user --upgrade
```

Then, try `poetry install` again.

____________________

Regarding your possible solution:
Updating the versions in the `poetry.lock` file may resolve the issue, doing it manually is not recommended.
Usually, the way to go is to run `poetry update`

**Comment by Flova** [comment]
Also thank you @zhengpengen for providing all the necessary information requested in the template!

I see you also commented on the upstream issue https://github.com/pytorch/pytorch/issues/47354

I would agree with @jaagut regarding his suggestions. While I am only testing for Ubuntu and Arch Linux it seems like it is working for other Windows 10 users so I guess it has something to do with the pip, poetry or nvidia driver (quite unlikely) versions.  Sadly the upstream issue is closed without a real fix, otherwise, I would suggest moving the issue there but that would be non-ideal in this case.

**Comment by Flova** [comment]
> Regarding your possible solution:
> Updating the versions in the `poetry.lock` file may resolve the issue, doing it manually is not recommended.
> Usually, the way to go is to run `poetry update`

If you want to specify a special version for a certain package pin the version in the `pyproject.toml` and generate a new dependency graph (`poetry.lock`) based on these requirements. This is done ad @jaagut said via `poetry update`.

**Comment by zhengpengen** [comment]
After updating the toml file to: 
[newtoml.txt](https://github.com/eriklindernoren/PyTorch-YOLOv3/files/6793487/newtoml.txt)
 running poetry update and poetry install didn't yield any problems.

**Comment by zhengpengen** [comment]
However, when I'm trying to download the weights, running ```./weights/download_weights.sh``` before and after ```poetry shell``` yields:
>'.' is not recognized as an internal or external command, operable program or batch file.

I have also tried to changing ```.sh``` into ```.bash``` but it also yields the same result.

Something else I tried was ```cd weights``` followed by ```poetry run download_weights.sh``` outside of and inside of ```poetry shell``` and this is what I got:

  OSError

  [WinError 193] %1 is not a valid Win32 application

  at ~\anaconda3\lib\subprocess.py:1311 in _execute_child
      1307│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1308│
      1309│             # Start the process
      1310│             try:
    → 1311│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1312│                                          # no special security
      1313│                                          None, None,
      1314│                                          int(not close_fds),
      1315│                                          creationflags,

If I just do ```cd weights``` and follow it with ```download_weights.sh```  it yields:
![image](https://user-images.githubusercontent.com/60248484/125126410-add9b200-e0c0-11eb-95cd-ab0e1379e7c1.png)
Despite the fact that when I run or try to upgrade wget using pip3 all requirements are satisfied.

Though if I do run the coco script by doing ```cd data``` and than ```get_coco_dataset.sh``` even outside of poetry shell, it runs successfully. 

However if I do ```cd data``` and ```poetry run get_coco_dataset.sh``` the same error as the weights file happen.

A few questions:
1. Are there workarounds to the weights problem
2. Is there a known reason why poetry run and such doesn't work
3. If there isn't a known reason yet, should I start a new issue for documentation purposes

**Comment by Flova** [comment]
The file is a bash script which is afaik not supported by default in windows. This is independent of poetry and uses `wget` which is a command in most linux distros. It is expected, that it doesn't work out of the box. But you got a point there. Could you open an issue requesting the bash scripts in python for better cross platform compatibility?

**Comment by Flova** [comment]
The weights download is also easy by hand, the coco dataset is a bit harder on the other hand.
If you have a look inside this file it should only download these files and place them inside the `weights` directory:
https://pjreddie.com/media/files/yolov3.weights
https://pjreddie.com/media/files/yolov3-tiny.weights
https://pjreddie.com/media/files/darknet53.conv.74

**Comment by zhengpengen** [comment]
> Though if I do run the coco script by doing `cd data` and than `get_coco_dataset.sh` even outside of poetry shell, it runs successfully.

Upon closer inspection, the only parts that ran successfully in ```get_coco_dataset.sh``` are the following code:
# Successfully Ran
#!/bin/bash

#CREDIT: https://github.com/pjreddie/darknet/tree/master/scripts/get_coco_dataset.sh

#Clone COCO API
git clone https://github.com/pdollar/coco
cd coco

mkdir images
cd images

# Unsuccessfully Ran
#Unzip
unzip -q train2014.zip
unzip -q val2014.zip

cd ..

#Download COCO Metadata
wget -c "https://pjreddie.com/media/files/instances_train-val2014.zip" --header "Referer: pjreddie.com"
wget -c "https://pjreddie.com/media/files/coco/5k.part" --header "Referer: pjreddie.com"
wget -c "https://pjreddie.com/media/files/coco/trainvalno5k.part" --header "Referer: pjreddie.com"
wget -c "https://pjreddie.com/media/files/coco/labels.tgz" --header "Referer: pjreddie.com"
tar xzf labels.tgz
unzip -q instances_train-val2014.zip

#Set Up Image Lists
paste <(awk "{print \"$PWD\"}" <5k.part) 5k.part | tr -d '\t' > 5k.txt
paste <(awk "{print \"$PWD\"}" <trainvalno5k.part) trainvalno5k.part | tr -d '\t' > trainvalno5k.txt

This resulted in the images folder being empty and I also don't see the instances_train-val.zip and other similar files in the folder.
After reading the README file in the original cocoapi repo I think I know where to download and unzip train2014.zip and val2014.zip, but I'm not as sure about the Coco metadata section. Ist here a workaround or instructions on how to handle those files?

**Comment by JBurtonBarr** [comment]
Hey,

Anyone else who has some across this issue I got around it using:
       pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

In normal CMD and then running the same command in poetry shell and it worked. Not sure exactly why the torchvision version could not be found but it said only torchvision version "1.2.0... 0.9.0, 0.10.0" could be found

**Comment by Yevgnen** [comment]
Got the same issue when trying to install torchaudio 0.12.1.

RuntimeError

      Unable to find installation candidates for torchaudio (0.12.1)

      at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
           68│ 
           69│             links.append(link)
           70│ 
           71│         if not links:
        →  72│             raise RuntimeError(
           73│                 "Unable to find installation candidates for {}".format(package)
           74│             )
           75│ 
           76│         # Get the best link
